# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-09T18:04:43Z"
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  containers:
  - args:
    - rabbitmq-server
    image: docker.io/library/rabbitmq:3-management
    name: rabbitmq
    ports:
    - containerPort: 15672
      hostPort: 8081
    - containerPort: 5672
      hostPort: 5672
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath:  /var/lib/rabbitmq
      name: var-rabbitmq-host-1

  volumes:
  - hostPath:
      path: /lvm/var/rabbitmq
      type: Directory
    name: var-rabbitmq-host-1

