kind: Deployment
apiVersion: apps/v1
metadata:
  name: lvmscp
  namespace: lvm-actors
  labels:
    k8s-app: lvmscp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: lvmscp
  template:
    metadata:
      name: lvmscp
      labels:
        k8s-app: lvmscp
    spec:
      containers:
        - name: lvmscp
          image: ghcr.io/sdss/lvmscp:rabbitmq-host
          env:
            - name: RABBITMQ_HOST
              value: 'rabbitmq-clusterip.lvm-services'
            - name: RABBITMQ_PORT
              value: '5672'
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          securityContext:
            privileged: false
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          hostPath:
            path: /data
      nodeName: lvm-spectro
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
