apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  hostNetwork: true
  nodeName: lvm-tcc
  containers:
    - name: samplepod
      command: ['/bin/ash', '-c', 'trap : TERM INT; sleep infinity & wait']
      image: alpine
