kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: lvm-jupyter
  name: lvm-jupyter
  namespace: lvm-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lvm-jupyter
  template:
    metadata:
      name: lvm-jupyter
      labels:
        app: lvm-jupyter
    spec:
      nodeName: lvm-hub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      containers:
        - args:
            - start-notebook.sh
            - --LabApp.token=''
          image: ghcr.io/sdss/lvmjupyter:latest
          name: lvm-jupyter
          ports:
            - containerPort: 8888
              hostPort: 8082
          stdin: true
          tty: true
          env:
            - name: NB_USER
              value: 'lvm'
            - name: NB_PASS
              value: ''
            - name: GRANT_SUDO
              value: 'yes'
            - name: RMQ_URL
              value: 'amqp://guest:guest@10.8.38.21:5672/'
            - name: LVM_DEBUG
              value: 'yes'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
