kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
  namespace: lvm-services
  labels:
    k8s-app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      creationTimestamp: null
      labels:
        k8s-app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11.7-management
          ports:
            - containerPort: 15672
            - containerPort: 5672
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      nodeName: lvm-hub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer
  namespace: lvm-services
spec:
  selector:
    k8s-app: rabbitmq
  ports:
    - name: 'api'
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: 'management'
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 10.8.38.21
